// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wbcaxibjwlxlqmmcoefp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndiY2F4aWJqd2x4bHFtbWNvZWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwODU4OTcsImV4cCI6MjA2NTY2MTg5N30.Zq4NhD-yA2Xh_bhMNmKbrqNOUEP8Kj0I4MmIhN58Kyo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);